### ISSUE TITLE
OpenViX 6.5.003.005 crash with E2-DarkOS (latest changes)

### ISSUE THREAD

**Issue by Orlandoxx** [DimitarCC/E2-DarkOS-skin#7]
Hello,

skin is crashing when pressing MENU button on remote.

< 18826.455259> 11:40:06.4142 [InfoBarGenerics] Key: 139 (Make) KeyID='KEY_MENU' Binding='('MENU',)'.
< 18826.455626> 11:40:06.4145 [ActionMap] Keymap 'InfobarMenuActions' -> Action = 'mainMenu'.
< 18826.457801> 11:40:06.4167 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/setup_selection.svg 48x48 from 192x192
< 18826.458954> 11:40:06.4179 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/plugin_selection.svg 48x48 from 192x192
< 18826.460136> 11:40:06.4191 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/timer_edit.svg 48x48 from 192x192
< 18826.461070> 11:40:06.4200 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/info_screen.svg 48x48 from 192x192
< 18826.462020> 11:40:06.4209 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/standby.svg 48x48 from 144x144
< 18826.464863> 11:40:06.4238 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/missing.svg 48x48 from 192x192
< 18826.465541> 11:40:06.4245 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/missing.svg 48x48 from 192x192
< 18826.466177> 11:40:06.4251 [ePNG] loadSVG /usr/share/enigma2/E2-DarkOS/menu/missing.svg 48x48 from 192x192
< 18826.467667> 11:40:06.4266 [Skin] Processing screen 'menu_mainmenu' from list 'menu_mainmenu, Menu', position=(0, 0), size=(1920 x 1080) for module 'MainMenu'.
< 18826.483339> 11:40:06.4423 [ePNG] loadSVG /usr/share/enigma2/logos/boxlogo.svg 630x64 from 776x174
< 18826.486711> 11:40:06.4456 [Skin] Processing screen 'MenuSummary' from list 'menu_mainmenu_summary, Menu_summary, MenuSummary, SimpleSummary', position=(0, 0), size=(800 x 480) for module 'MenuSummary'.
< 18826.492420> 11:40:06.4513 Traceback (most recent call last):
< 18826.492889> 11:40:06.4518   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 58, in action
< 18826.493443> 11:40:06.4524   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 1556, in mainMenu
< 18826.493821> 11:40:06.4527   File "/usr/lib/enigma2/python/StartEnigma.py", line 150, in openWithCallback
< 18826.494524> 11:40:06.4534     dialog = self.open(screen, *arguments, **kwargs)
< 18826.495224> 11:40:06.4541              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
< 18826.495292> 11:40:06.4542   File "/usr/lib/enigma2/python/StartEnigma.py", line 161, in open
< 18826.495807> 11:40:06.4547     self.execBegin()
< 18826.495963> 11:40:06.4549   File "/usr/lib/enigma2/python/StartEnigma.py", line 87, in execBegin
< 18826.496353> 11:40:06.4553     currentDialog.show()
< 18826.496530> 11:40:06.4554   File "/usr/lib/enigma2/python/Plugins/Extensions/LCD4linux/plugin.py", line 2934, in L4L_replacement_Screen_show
< 18826.501705> 11:40:06.4606     Screen.L4L_show_old(self)
< 18826.501909> 11:40:06.4608   File "/usr/lib/enigma2/python/Screens/Screen.py", line 135, in show
< 18826.502411> 11:40:06.4613   File "/usr/lib/enigma2/python/Components/Addons/Pager.py", line 46, in onContainerShown
< 18826.502785> 11:40:06.4617   File "/usr/lib/enigma2/python/Components/Addons/Pager.py", line 199, in initPager
< 18826.503152> 11:40:06.4621   File "/usr/lib/enigma2/python/Components/Addons/Pager.py", line 155, in getSourceOrientation
< 18826.503686> 11:40:06.4626 AttributeError: 'NoneType' object has no attribute 'master'
< 18826.503777> 11:40:06.4627 [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xaeea82a0>>,('InfobarMenuActions', 'mainMenu')) failed)

**Comment by DimitarCC** [comment]
That is because of the LCD4Linux plugin that you use...I dont use it and no crashes here...
But i proposed a [pull](https://github.com/OpenViX/enigma2/pull/1015) regarding that crash

**Comment by DimitarCC** [comment]
Its not skin issue so i close this here ;)

**Comment by Huevos** [comment]
@Orlandoxx have you got Skype?

**Comment by Orlandoxx** [comment]
Nope.

**Comment by Huevos** [comment]
Can you load it?

**Comment by Orlandoxx** [comment]
Done
